2021-10-28 17:23:30,247 INFO    MainThread:590057 [wandb_setup.py:_flush():69] setting env: {}
2021-10-28 17:23:30,248 INFO    MainThread:590057 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-28 17:23:30,248 INFO    MainThread:590057 [wandb_init.py:_log_setup():348] Logging user logs to /home/ingambe/DeepLearningCourse/3-Deep-networks/Slides/wandb/run-20211028_172330-20qz1adq/logs/debug.log
2021-10-28 17:23:30,248 INFO    MainThread:590057 [wandb_init.py:_log_setup():349] Logging internal logs to /home/ingambe/DeepLearningCourse/3-Deep-networks/Slides/wandb/run-20211028_172330-20qz1adq/logs/debug-internal.log
2021-10-28 17:23:30,250 INFO    MainThread:590057 [wandb_init.py:_jupyter_setup():300] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f3659ea85b0>
2021-10-28 17:23:30,251 INFO    MainThread:590057 [wandb_init.py:init():381] calling init triggers
2021-10-28 17:23:30,251 INFO    MainThread:590057 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {}
2021-10-28 17:23:30,251 INFO    MainThread:590057 [wandb_init.py:init():430] starting backend
2021-10-28 17:23:30,252 INFO    MainThread:590057 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-28 17:23:30,280 INFO    MainThread:590057 [backend.py:ensure_launched():135] starting backend process...
2021-10-28 17:23:30,299 INFO    MainThread:590057 [backend.py:ensure_launched():139] started backend process with pid: 590089
2021-10-28 17:23:30,304 INFO    MainThread:590057 [wandb_init.py:init():435] backend started and connected
2021-10-28 17:23:30,388 INFO    MainThread:590057 [wandb_run.py:_label_probe_notebook():819] probe notebook
2021-10-28 17:23:30,394 INFO    MainThread:590057 [wandb_run.py:_label_probe_notebook():826] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-10-28 17:23:30,394 INFO    MainThread:590057 [wandb_init.py:init():494] updated telemetry
2021-10-28 17:23:30,396 INFO    MainThread:590057 [wandb_init.py:init():517] communicating current version
2021-10-28 17:23:35,398 INFO    MainThread:590057 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-10-28 17:23:36,785 INFO    MainThread:590057 [wandb_init.py:init():557] starting run threads in backend
2021-10-28 17:23:39,919 INFO    MainThread:590057 [wandb_run.py:_console_start():1605] atexit reg
2021-10-28 17:23:39,920 INFO    MainThread:590057 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.WRAP
2021-10-28 17:23:39,920 INFO    MainThread:590057 [wandb_run.py:_redirect():1516] Wrapping output streams.
2021-10-28 17:23:39,921 INFO    MainThread:590057 [wandb_run.py:_redirect():1540] Redirects installed.
2021-10-28 17:23:39,922 INFO    MainThread:590057 [wandb_init.py:init():582] run started, returning control to user process
2021-10-28 17:23:39,925 INFO    MainThread:590057 [wandb_init.py:_pause_backend():262] pausing backend
2021-10-28 17:23:39,925 INFO    MainThread:590057 [jupyter.py:save_ipynb():301] looking for notebook: 3-Deep-networks/Slides/3-Visualize NN.ipynb
2021-10-28 17:23:39,934 INFO    MainThread:590057 [wandb_init.py:_resume_backend():271] resuming backend
2021-10-28 17:23:40,076 INFO    MainThread:590057 [wandb_init.py:_pause_backend():262] pausing backend
2021-10-28 17:23:40,076 INFO    MainThread:590057 [jupyter.py:save_ipynb():301] looking for notebook: 3-Deep-networks/Slides/3-Visualize NN.ipynb
2021-10-28 17:24:05,656 INFO    MainThread:590057 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-10-28 17:24:05,657 INFO    MainThread:590057 [wandb_run.py:_restore():1547] restore
2021-10-28 17:24:06,471 INFO    MainThread:590057 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 810
}

2021-10-28 17:24:06,929 INFO    MainThread:590057 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 810
}

2021-10-28 17:24:07,847 INFO    MainThread:590057 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  total_bytes: 10314
}

2021-10-28 17:24:07,953 INFO    MainThread:590057 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  total_bytes: 10456
}

2021-10-28 17:24:08,057 INFO    MainThread:590057 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  total_bytes: 10456
}

